### PR TITLE
added wildcard filter

### PR DESCRIPTION
**Pull request by ferronrsmith**

### CODE REVIEW

**Comment by danpaz** [comment]
👍  Thanks for the PR @ferronrsmith ! I noticed there's more than just the wildcard filter being implemented here, could you separate the fuzzy filter and sorting on multiple fields features into separate PRs? I have some questions about both of those, which I can summarize here:

1. fuzzy filter -- does this exist? I couldn't find any docs on it, I see [fuzzy query](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-fuzzy-query.html) but not fuzzy filter. Possibly I'm missing something.
2. sorting on multiple fields: we should think a little about the best approach here. Do we need a separate api `sorts` or can we beef up `sort` to handle both single and multiple sorts? And should `sort` be chainable? i.e. should we support doing `.sort('channel', 'desc').sort('categories', 'desc').sort('content', 'asc')` to get multiple sorts?

The wildcard filter itself LGTM.

**Comment by ferronrsmith** [comment]
Yes that was a change added in elasticsearch 2.3. All query/filter clause can be used interchangeably.

https://www.elastic.co/guide/en/elasticsearch/reference/2.3/breaking_20_query_dsl_changes.html#_queries_and_filters_merged

**Comment by ferronrsmith** [comment]
2. I like the second approach. Beef up to allow chaining, but I would still need the array support. It's convenient, since sort for me is auto-generated https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-sort.html

**Comment by danpaz** [comment]
Closing in favor of #24 #25 #26

**Pull request closed without merging**
