### PR TITLE
Release bodybuilder 2

### PR DESCRIPTION
**Pull request by danpaz**
Making this PR for when bodybuilder 2 is ready for release.

🎉

### CODE REVIEW

**Comment by johannes-scharlach** [comment]
I'm really really happy that the project is coming along like this! Thanks for all your hard work @danpaz !

**Comment by ferronrsmith** [comment]
any eta on this release ? Already using the beta in production and it's looking good!

**Comment by danpaz** [comment]
Good to hear it's working for you @ferronrsmith 😄 . 

The only blocker left in my mind is in #81 "Figure out how to link to the old bodybuilder 1 documentation." I don't yet have a good idea for this. But perhaps its not worth worrying about, if people want to see the old documentation they can checkout the 1.x branch and `npm run build:docs` locally. Any thoughts on that approach?

**Comment by ferronrsmith** [comment]
@danpaz it's a tricky problem since the documentation is being generated from the source. I see 2 options really.

1. Have a separate repository for managing documentation (Mixture of shell scripts to pull and generate 2 different versions of the docs)

|  Version | Location   |
|---|---|
| v1  |   docs/version1  |
| v2  |   docs/version2  |

2. Always maintain the latest version of the doc for the website and generate markdown for old versions. 
    So `/docs/index.html` => `/docs/index.md` (you can reference the v1 documentation in v2)

**Comment by danpaz** [comment]
@ferronrsmith I like the idea of archiving documentation for v1 in a md file and linking to that from the current documentation. Nice and simple.

**Comment by ferronrsmith** [comment]
@danpaz Agreed.

**Comment by johannes-scharlach** [comment]
You can also just link to the markdown file with the tag `v1.24.0` https://github.com/danpaz/bodybuilder/blob/v1.24.0/docs/API.md with no need for manual archiving (maybe that's what you meant?)

**Comment by ferronrsmith** [comment]
Yea that's the idea

**Comment by danpaz** [comment]
Yup sounds good to me. I'll try to get that done tonight, or anyone else is free to beat me to it and make a MR off this branch :)

**Pull request merged**
