### PR TITLE
avoid '.should' prototype property

### PR DESCRIPTION
**Pull request by johannes-scharlach**
This is an attempt at fixing #122, the issue where there is a `Object.prototype.should` defined.

I've tried to create a test case, but I had run-time errors rather than problems with the result, so I didn't add my test. If you have any ideas on how to test, I'd be happy to hear about it.

### CODE REVIEW

**Comment by ferronrsmith** [comment]
to be honest I don't think we should fix this. It's easier to just run in `noConflict` mode

**Comment by ferronrsmith** [comment]
I have an idea for the test case. Give me a few

**Comment by ferronrsmith** [comment]
Ok wrote a test and it still failed with `should.js` for me

```javascript
import test from 'tape'
import bodyBuilder from '../src'
import should from 'should

test('bodyBuilder should build query with no field', (t) => {
    t.plan(1)

    const result = bodyBuilder().orFilter('term', 'email', 'kimchee@kimchee.com')
        .orFilter('term', 'username', 'kimchee').build()

    console.log(JSON.stringify(result))

    should(result).deepEqual(
        {
            query: {
                bool: {
                    filter: {
                        bool: {
                            should: [
                                {
                                    term: {
                                        email: 'kimchee@kimchee.com'
                                    }
                                },
                                {
                                    term: {
                                        username: 'kimchee'
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        }
    )
})

```

**Comment by johannes-scharlach** [comment]
@ferronrsmith the whole issue bugged me way too much still, so I proceeded to solve the issue.

I've created a test case based on your example that doesn't require a dependency to `should`.

So what's going on here:
1. I'm extending the `Object.prototype` with a `should` property. This is done pretty similar to how shouldjs does it.
2. when the `_.merge` is happening, the should property is suddenly lost. I've worked around this by using `_.set` in the right order.

I found it to be an interesting challenge with `Object.prototype`, but generally agree that shouldjs is behaving badly here.

**Comment by ferronrsmith** [comment]
Tested this with a project with `should.js` and it still fails.

**Comment by johannes-scharlach** [comment]
I give up...

**Comment by ferronrsmith** [comment]
Problem is with should overriding the object prototype. I'm sure this isn't a bodybuilder only problem. The best course is to use the noConflict mode

**Pull request closed without merging**
