### PR TITLE
minior edits to typings

### PR DESCRIPTION
**Pull request by ferronrsmith**

### CODE REVIEW

**Comment by ferronrsmith** [comment]
resolves #178

**Comment by jacobwgillespie** [comment]
Hey, was just about to open a PR that does something very similar to this (https://github.com/danpaz/bodybuilder/compare/master...jacobwgillespie:update-typescript?expand=1).  Right now aggregations that don't target a field are type errors in TS:

```typescript
bodybuilder()
  .aggregation('top_hits', {...}, 'name')
```

I believe this PR should resolve that issue.

**Comment by ecdeveloper** [comment]
When is this expected to be merged?

**Comment by ferronrsmith** [comment]
@jacobwgillespie can you test this branch to see if it fixes your issues ? On a ✈️

**Comment by danpaz** [comment]
Cool thanks all, I'll merge and release.

**Comment by ferronrsmith** [comment]
Thanks @danpaz

**Pull request merged**
