### PR TITLE
Add function_score query

### PR DESCRIPTION
**Pull request by evgenypoyarkov**
Hi, I've added the function_score queries. Currently that feature looks pretty raw, but covers the case.
Later I'd like to see it as a chain of functions.

### CODE REVIEW

**Comment by danpaz** [comment]
Looks good @evgenypoyarkov, thanks for the PR! CI seems to be failing due to use of Object.assign in node 0.12 and 0.10. I think if you replace that with lodash's `assign` that should work as expected.

**Comment by vladgolubev** [comment]
@evgenypoyarkov any plans to adjust the PR ?

**Comment by evgenypoyarkov** [comment]
@danpaz @vladgolubev Updated the PR. Tests are passed now.

**Comment by danpaz** [comment]
👍 LGTM.

**Pull request merged**
