### PR TITLE
Add minimumShouldMatch for bool.should queries

### LINKED ISSUE #114: minimum_should_match?
What's the correct way to be able to add a `minimum_should_match` option to a filtered `should`? I'm trying to end up with something like the following:

```
"filter": {
  "bool": {
    "should": [
      {
         "match": {
             "field_name": "foo"
          }
       },
       {
           "match": {
             "field_name": "bar"
            }
         },
         {
            "match": {
               "field_name": "baz"
            }
         }
     ],
      "minimum_should_match": "2<70%"
  }
}
...
```
I can get the `match` values in the filter using something like the following:
```
params[key].forEach(param => {
    builder.orFilter('match', 'field_name', param);
})
```
but no matter where I try and add `minimum_should_match` (as an option of each of the above `orFilter` calls, or as a separate `orFilter` call after the above) I get an invalid query. Seems that `bodybuilder` simply tries to add it as a new object in the filter. 

Any idea about how the above can be done?

### PR DESCRIPTION
**Pull request by danpaz**
Resolves #114. 

@mikeholmesuk @diegoprd can either or both of you pull this branch and give this a try? Any thoughts?

```js
bodybuilder()
  .orQuery('foo')
  .orQuery('bar')
  .minimumShouldMatch(2)
  .build()
```

TODO 
- [ ] jsdoc for this method

### CODE REVIEW

**Comment by mikeholmesuk** [comment]
Sorry for the delay in getting back to you, have been busy on other parts of the project I'm working on. Sure, I'll pull this today and give it a try and get back to you. Thanks.

**Comment by mikeholmesuk** [comment]
Good job. Have checked this and it works great. If the above example could be included in the docs it would be really useful for anyone coming to this after me. 

Keep up the good work 👍

**Comment by ferronrsmith** [comment]
Looks good, but this needs to also be available to the `filterBuilder`

**Comment by diegoprd** [comment]
So sorry for the delay guys..
Yes, I agree with @ferronrsmith looks good and thanks @danpaz for your work... but I think is also needed in the `filter-builder.js`.

**Comment by danpaz** [comment]
Agreed that it is needed in filter-builder also, but since the queryBuilder and filterBuilder modules are [assigned to the same object](https://github.com/danpaz/bodybuilder/blob/master/src/index.js#L150-L151), they can't both have the same function called `minimumShouldMatch` otherwise the second one will override the first.

For simplicity, we could name these queryMinimumShouldMatch and filterMinimumShouldMatch so there is no ambiguity (at the cost of some very long function names!).

**Comment by ferronrsmith** [comment]
Sounds good to me

**Comment by ferronrsmith** [comment]
When will this be merged ? Need this feature ASAP

**Comment by danpaz** [comment]
This is now published in 2.1.0
http://bodybuilder.js.org/docs/#queryminimumshouldmatch

**Comment by diegoprd** [comment]
Great! thanks you guys!

**Pull request merged**
