### PR TITLE
Optimize mergeConcat

### PR DESCRIPTION
**Pull request by nfantone**
Hi, @danpaz.

I've been playing around with *bodybuilder* and notice that, when there was a relative large number of `body.query` calls, chaining methods on the builder would take _a lot_ of time, causing serious bottlenecks on my application. And that number need not be _that_ large: with ~1000 calls, it takes around ~8s to create a query. With just a 100 you can feel the impact. Increase that to 10k, and the builder _never_ completes its job (I mean, it does eventually - I just got bored of waiting to bring you a time estimate).

I started to browser through the source code and I dug out the culprit: `_.merge` on [this line](https://github.com/danpaz/bodybuilder/blob/master/src/utils.js#L22). So, I wrote a custom `Object.assign`-like function that replaces its usage, but maintains the original `mergeConcat` functionality.

My test case was very dull:

```javascript
'use strict';
const Bodybuilder = require('./lib');
const body = new Bodybuilder();
let start = Date.now();
for (let i = 0; i < 10000; i++) {
  body.query('match', 'message', 'this is a test');
}
let q = body.build('v2');
console.log(q);
console.log(`'query.bool.must' length: ${q.query.bool.must.length}`);
console.log(`Took ${Date.now() - start}ms`);
```

The result:

### With new custom `mergeConcat` function

```sh
→ node test-perf.js
{ query: { bool: { must: [Object] } } }
'query.bool.must' length: 10000
Took 120ms
```

### With `_.merge`. 
With 10000 iterations (as the snippet above shows), the scripts just runs forever. Here's the result with 1000 iterations:

```sh
→ node test-perf.js
{ query: { bool: { must: [Object] } } }
'query.bool.must' length: 1000
Took 7217ms
```

You can already see the difference is huge.

I've also upgraded lodash to latest, since my first approach was to see if there was any performance to be gained by just upgrading the library. It turn out there wasn't, but it also didn't harm the project.

### CODE REVIEW

**Comment by danpaz** [comment]
@nfantone This is cool, thanks! Code LGTM, but a few questions and TODOs for you:
- [ ] Can you tell me what your use case is where you need to make 100+ query clauses? The performance of mergeConcat seems unlikely to me to be a concern for the vast majority of users, but I may be wrong on that.
- [ ] Can this be achieved by using _.assign instead of _.merge? I think that method has better performance (see https://github.com/lodash/lodash/issues/1865) 
- [ ] Improve test coverage for mergeConcat, there's only one test case right now so this is a good time to revisit this.

Again it seems like this will work just fine, I just want to justify the additional complexity introduced by rolling our own rather than using a very well tested library like lodash. Thanks!

**Comment by nfantone** [comment]
Hi, @danpaz. Thanks for your input! My answers below:

1) Well... to be honest, chaining hundreds of `query` calls is not _exactly_ my use case. We've recently migrated an app that was building complex dynamic ES queries manually (ie, gigantic sequential `if`s) to _bodybuilder_. And after the upgrade was completed, we noticed that performance had taken a toll, severely. My subsequent research led to this PR. It doesn't really need to be 100 `bool` queries: put together a good number of them, running in parallel, add concurrent users to the mix and get yourself a bottleneck.
2) It may work, yes. I could try using `_.assign` with a `customizer` function for arrays.
3) Ok. I'm on it.

>  I just want to justify the additional complexity introduced by rolling our own rather than using a very well tested library like lodash.

The thing is, "well tested libraries" like lodash tend to tackle a broader spectrum of use cases, focusing on generic usages. Just browse through its sources a little bit and see that it just `function` call through `function` call all around, jumping between re-usable bits of code. Since my focus was performance, I opted for rolling my own custom, inline function: for small, focused scenarios like this one lodash just can't compete with that.

**Comment by nfantone** [comment]
@danpaz There. I've replaced my custom function for _almost_ exactly the same thing you had before, but using `_.assignWith` instead of `_.merge`. Happy to say performance is similar to my original solution. So, good call!

**Comment by nfantone** [comment]
@danpaz Added more `mergeConcat` unit tests. Can't think of anything more to test for that tiny function.

**Comment by danpaz** [comment]
Looks great! 💯 Can you run `npm run build:browser` to update the browser build and commit that? Then I think this is ready and I'll cut a new minor release.

**Comment by nfantone** [comment]
@danpaz There you go.

Not that I mind the extra work, but I'll take this opportunity to ask: why isn't the build part of a... well, a _build_ process. Why are you versioning the output of Babel? Wouldn't it be better if this tasks only ran when you intend to publish your artifacts?

**Comment by danpaz** [comment]
> Why are you versioning the output of Babel? 

The output of babel has to be part of the module because that is the code that has to be loaded. And there have been a few times the babel compile step fails for various reasons, so its good to make sure that that process succeeds at the PR stage.

> Wouldn't it be better if this tasks only ran when you intend to publish your artifacts?

Yes! This is the first time its come up, are you thinking a `npm run prepublish` script? Feel free to open a PR if you have a good approach in mind!

**Pull request merged**
