### PR TITLE
Angular 1.x build. Module 'Bodybuilder' exposes factory 'BodyFactory'…

### PR DESCRIPTION
**Pull request by kennyczadzeck**
… which can be registered as a service to use in Angular 1.x applications.

### CODE REVIEW

**Comment by danpaz** [comment]
Thanks @kennyczadzeck! 

I'm not too familiar with Angular, can you describe what the usage in an app would look like? Is there anything specific about this implementation that would make it usable only in Angular, or can we generalize it and be framework agnostic?

Also can you write out the steps you used to create this build? We might consider adding this to the `npm run build` script.

**Comment by kennyczadzeck** [comment]
No problem. An Angular app is essentially an MVC-based collection of modules (or packages) injected as dependencies into a top-level module.

This minified build is just such a dependency module which exposes a "factory" called "BodyFactory". An Angular factory is a singleton object which produces other objects, either directly (such as this case) or as a client for external service(s).

The interface is just about the same as in a Node environment. To build the body of a search request:
```
// Angular application instance
var app = angular.module("myApp", "'ui.bootstrap", "elasticsearch", "Bodybuilder"]);

// Expose ElasticSearch client to Angular app
app.service("es", ["esFactory", function(esFactory) {
	return esFactory({
		host: "localhost:9200",
	});
}]);

// Expose BodyBuilder library to Angular app
app.service("Bodybuilder", ["BodyFactory", function(BodyFactory) {
	return BodyFactory
}]);

var esSearchData = {
	index: $scope.search.index,
	body: new Bodybuilder()
		.query("match", "_all", $scope.search.text)
		.build()
};

// Query ElasticSearch and return data
var searchEs = function() {
	searchData = buildSearchData();
	es.search(searchData).then(function(body) {
		$scope.hits = body.hits.hits.map(function(hit) {
			hit._source["type"] = hit._type;
			return hit._source
		});
			console.log($scope.hits);
		}, function(err) {
			console.trace(err.message);
	});
};
```

To do the build, I used [Browserify](http://browserify.org/) which compiles Node modules into single files which can be requested by the browser. I then used [Uglify.js](https://github.com/mishoo/UglifyJS) to minify that file.

I can also provide a jQuery build and a pure JS build as well.

**Comment by danpaz** [comment]
Ok, I think I follow now. It sounds like what you're proposing is to:
* Bundle and minify the `lib` directory of this project using browserify/uglify, essentially concatenating all the files together and exposing the Bodybuilder via a global, `window.Bodybuilder`.
* Include the `app.module` and `app.service` code above to the bundle and instruct Angular users to use `BodyFactory` in their code.

Does that sound right?

I don't think it's really necessary to provide a angular 1x specific build, it might make more sense to provide a commonjs or umd module so that any framework (or pure JS) can use it. [Webpack](https://webpack.github.io/docs/configuration.html) could work well for this.

**Comment by danpaz** [comment]
Check out my comment #5 and please let me know if this solves your use case!

**Pull request closed without merging**
