### PR TITLE
Queries/nested query

### PR DESCRIPTION
**Pull request by msanguineti**
Hello,

I've made this quick PR for nested queries, i.e. queries over nested objects. Also updated the docs section.

Anything missing?

### CODE REVIEW

**Comment by danpaz** [comment]
@msanguineti Thanks for getting the ball rolling on this 👍! This approach works, however it leaves the bulk of the query building to the user. What do you think about an approach similar to how `nested` filters have been implemented [here](https://github.com/danpaz/bodybuilder/blob/master/src/filters/nested-filter.js)? This way the api might look something like:

```js
new Bodybuilder()
        .query('nested', 'name', 'term', 'user', 'kimchy')
        .build()
```

**Comment by danpaz** [comment]
Related to https://github.com/danpaz/bodybuilder/issues/36.

**Comment by msanguineti** [comment]
@danpaz indeed this is a very quick PR, but with what you propose how would the API give me this:

```
{
    "nested" : {
        "path" : "obj1",
        "score_mode" : "avg",
        "query" : {
            "bool" : {
                "must" : [
                    {
                        "match" : {"obj1.name" : "blue"}
                    },
                    {
                        "range" : {"obj1.count" : {"gt" : 5}}
                    }
                ]
            }
        }
    }
}
```

What I do is to create a **match query** and a **range filter**, then I create a **bool query (must)** to which I pass the _[match, range]_ object. Finally, I pass this big object into the **nested query**. Of course the nested query is within something else as well...

So what is needed is a generic mechanism to nest/embed/compose queries and filters. At the very first level yes, something like nested filters is necessary so that the user passes parameters and the API builds the query/filter, but then you might need to start composing things.

Maybe I am missing something here :) so please correct me if I am talking out of my backside.

**Comment by danpaz** [comment]
> So what is needed is a generic mechanism to nest/embed/compose queries and filters.

I think that's exactly right. There's discussion around this idea in #65, creating a generic API for queries/filters/aggregations which can be more easily composed. I can push the local branch that I've been experimenting with later today and I would love your feedback!

**Comment by msanguineti** [comment]
I've checked out your experimental branch. I will report back but first impression is good, this is the right track.

**Comment by danpaz** [comment]
The next version of bodybuilder will support `nested` queries, give it a try by installing the beta release:

```
npm install bodybuilder@beta
```

And see [this example](https://github.com/danpaz/bodybuilder/blob/prerelease-bodybuilder-2/test/query-builder.js#L412-L438) for its usage.

If this doesn't solve your issue please reopen!

**Pull request closed without merging**
