### PR TITLE
Add TypeScript type definitions

### PR DESCRIPTION
**Pull request by jacobwgillespie**
This PR adds TypeScript type definitions for bodybuilder - the existing JSDoc comments and the clean code made it quite easy, so thanks for that.  👍

### CODE REVIEW

**Comment by danpaz** [comment]
@jacobwgillespie thanks for this! I'm not a TS user myself, what's the best way to test this out?

**Comment by jacobwgillespie** [comment]
@danpaz no problem!

Here's a sample repo for you to play with: https://github.com/jacobwgillespie/bodybuilder-ts-example.  You should be able to edit `src/index.ts` it an editor like VS Code that understands TypeScript to see type completion, or run `yarn check` to run the code through the TypeScript checker.  The example from the homepage is in there as well as an example with a sub-aggregation and a commented-out example that is full of errors.

If anything goes wrong with the `yarn install`, take a look at `scripts/install-ts-typedef.sh`, which basically just patches bodybuilder's `package.json` to reference the types, as a simulation of what would be installed from npm.

**Comment by ferronrsmith** [comment]
@jacobwgillespie Just wondering. Shouldn't this be submitted to [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped). VS Code/Webstorm already have plugins that integrate with it.

**Comment by jacobwgillespie** [comment]
@ferronrsmith as I understand it, it's preferable for the module to maintain its own type definitions as then they are "closer to home" and thus are much easier to keep in sync with changes to the parent package.  DefinitelyTyped allows the TS community to maintain TypeScript type definitions for modules without requiring that the module include the type inside it's package, so in that way it doesn't _require_ that each module change.  But then it's up to the community to keep everything in sync.  AFAIK, having bodybuilder own its own types is preferable.

See other modules like `redux`, `moment`, `axios`, etc for examples of modules including type definitions directly in their npm packages.

> VS Code/Webstorm already have plugins that integrate with it.

If bodybuilder includes types in its package, like with this PR, then any editor that understands TS will pick up the definitions just from the `npm install`, without any additional steps.

**Comment by ferronrsmith** [comment]
@jacobwgillespie I get what you're saying, either way is fine by me.

One change `sort` can be an array

```javascript
// http://bodybuilder.js.org/docs/#sort
bodybuilder()
 .sort([
   {"categories": "desc"},
   {"content": "asc"}
 ])
  .build()
```

**Comment by jacobwgillespie** [comment]
> `sort` can be an array

Nice catch, updated

**Comment by ferronrsmith** [comment]
This could be an array of {string:object}, not necessarily a string.

```javascript
bodyBuilder().sort([
    {
      _geo_distance: {
        'a.pin.location': [-70, 40],
        order: 'asc',
        unit: 'km',
        mode: 'min',
        distance_type: 'sloppy_arc'
      }
    },
    {
      _geo_distance: {
        'b.pin.location': [-140, 80],
        order: 'asc',
        unit: 'km',
        mode: 'min',
        distance_type: 'sloppy_arc'
      }
    }
  ])
  .sort([
    { timestamp: 'desc' },
    { content: 'desc' },
    { content: 'asc' },
   {"price" : {"order" : "asc", "mode" : "avg"}}
  ])
.build()
```

**Comment by ferronrsmith** [comment]
sort has a lot of "shortcuts"

```ts
sort(field: string): Bodybuilder;
sort(field: string, direction: string): Bodybuilder;
sort(field: string, body: object): Bodybuilder;
// all these options are also available in the array
sort(fields: Array<{[field: string]}>): Bodybuilder;
sort(fields: Array<{[field: string]: string}>): Bodybuilder;
sort(fields: Array<{[field: string]: object}>): Bodybuilder;
```

**Comment by ferronrsmith** [comment]
Add the above changes and we should be good to merge.

**Comment by ferronrsmith** [comment]
ok looks good. will merge after the build is green

**Comment by jacobwgillespie** [comment]
Okay, I've added them - this one here is invalid TypeScript:

```typescript
sort(fields: Array<{[field: string]}>): Bodybuilder;
```

I am assuming that this means it takes an array of strings, like so:

```javascript
bodybuilder().sort(['field', 'field'])
```

If that's correct, then this is what I put in there:

```typescript
sort(fields: string[]): Bodybuilder;
```

**Comment by danpaz** [comment]
👍 make sure to add yourself to contributors! 
https://github.com/danpaz/bodybuilder/blob/master/.all-contributorsrc
https://github.com/danpaz/bodybuilder/blob/master/package.json

**Comment by ferronrsmith** [comment]
Haha yea and I think you just found a bug too.

**Comment by jacobwgillespie** [comment]
Added myself as a contributor.  👍 

LMK if you need me to do anything about the bug.

**Comment by ferronrsmith** [comment]
If you want to tackle it that's fine

**Comment by ferronrsmith** [comment]
LGTM !

**Pull request merged**
