### PR TITLE
fixes invalid query nesting generation

### LINKED ISSUE #142: Invalid nested bool query with more "query", but works with "filter"
Example code:

```javascript
const bodybuilder = require('bodybuilder');
let body = bodybuilder();

body.query('bool', b => b
      .filter('term', 'field1', x)
      .filter('term', 'field2', x)
      .orFilter('term', 'field3', x));
body.query('bool', b => b
      .filter('term', 'field1', x)
      .filter('term', 'field2', x)
      .orFilter('term', 'field3', x));
````

Makes perfect, valid query:

```
{
  "query": {
    "bool": {
      "must": [
        {
          "bool": {
            "filter": {
              "bool": {
                "must": [
                  {
                    "term": {
                      "field1": 1
                    }
                  },
                  {
                    "term": {
                      "field2": 2
                    }
                  }
                ],
                "should": [
                  {
                    "term": {
                      "field3": 3
                    }
                  }
                ]
              }
            }
          }
        },
        {
          "bool": {
            "filter": {
              "bool": {
                "must": [
                  {
                    "term": {
                      "field4": 10
                    }
                  },
                  {
                    "term": {
                      "field5": 20
                    }
                  }
                ],
                "should": [
                  {
                    "term": {
                      "field6": 30
                    }
                  }
                ]
              }
            }
          }
        }
      ]
    }
  }
}
```

Change filters to queries:

```javascript
const bodybuilder = require('bodybuilder');
let body = bodybuilder();

body.query('bool', b => b
      .query('term', 'field1', x)
      .query('term', 'field2', x)
      .orQuery('term', 'field3', x));
body.query('bool', b => b
      .query('term', 'field1', x)
      .query('term', 'field2', x)
      .orQuery('term', 'field3', x));
````

And built query is invalid: 

```
{
    "error": {
        "root_cause": [
            {
                "type": "parsing_exception",
                "reason": "[bool] query does not support [query]",
                "line": 7,
                "col": 22
            }
        ],
        "type": "parsing_exception",
        "reason": "[bool] query does not support [query]",
        "line": 7,
        "col": 22
    },
    "status": 400
}
```

```
{
  "query": {
    "bool": {
      "must": [
        {
          "bool": {
            "query": {
              "bool": {
                "must": [
                  {
                    "term": {
                      "field1": 1
                    }
                  },
                  {
                    "term": {
                      "field2": 2
                    }
                  },
                  {
                    "term": {
                      "field3": 3
                    }
                  }
                ]
              }
            }
          }
        },
        {
          "bool": {
            "query": {
              "bool": {
                "must": [
                  {
                    "term": {
                      "field4": 10
                    }
                  },
                  {
                    "term": {
                      "field5": 20
                    }
                  },
                  {
                    "term": {
                      "field6": 30
                    }
                  }
                ]
              }
            }
          }
        }
      ]
    }
  }
}
```

### LINKED ISSUE #162: Nested bool query with must
I have a really difficult time trying to build this type of query
```
{
    "query": {
        "bool": {
            "must": {
                "bool" : { "should": [
                      { "match": { "title": "Elasticsearch" }},
                      { "match": { "title": "Solr" }} ] }
            },
            "must": { "match": { "authors": "clinton gormely" }},
            "must_not": { "match": {"authors": "radu gheorge" }}
        }
    }
}
```
Because when constructing the nested `bool` with a `should` inside, the library puts an extra `query` key there. So the output of this
```
bodybuilder()
        .query('match', 'message', 'this is a test')
	.query('bool', b => b.orQuery('match', 'm', 'asd').orQuery('match', 'm', 'dsa'))
        .build()
```
is 
```
{
  "query": {
    "bool": {
      "must": [
        {
          "match": {
            "message": "this is a test"
          }
        },
        {
          "bool": {
            "query": {
              "bool": {
                "should": [
                  {
                    "match": {
                      "m": "asd"
                    }
                  },
                  {
                    "match": {
                      "m": "dsa"
                    }
                  }
                ]
              }
            }
          }
        }
      ]
    }
  }
}
```
Which is not a valid query. But changing the query to a filter works fine:
```
bodybuilder()
	.query('match', 'message', 'this is a test')
	.filter('bool', b => b.orFilter('match', 'm', 'asd').orFilter('match', 'm', 'dsa'))
        .build()
```
with the following output
```
{
  "query": {
    "bool": {
      "filter": {
        "bool": {
          "should": [
            {
              "match": {
                "m": "asd"
              }
            },
            {
              "match": {
                "m": "dsa"
              }
            }
          ]
        }
      },
      "must": {
        "match": {
          "message": "this is a test"
        }
      }
    }
  }
}
```
Is this a bug or am I just missing something?
Thanks

### PR DESCRIPTION
**Pull request by ferronrsmith**
bodybuilder now generates valid nested query

fixes #142
fixes #162

### CODE REVIEW

**Comment by johannes-scharlach** [comment]
I think I've tried to address this in #144 but I'd also extended the tests and they broke after applying my changes.

Could you add the tests I've created in https://github.com/danpaz/bodybuilder/pull/144/commits/55d6aef8336b89b0ea4a52f9ce5144afe364c720 and see if they pass? (The changes are from August, so I don't remember everything exactly...)

**Comment by ferronrsmith** [comment]
Nope 

```javascript
/// this works
bodyBuilder().query('has_parent', 'parent_type', 'blog', (q) => {
    return q.query('term', 'tag', 'something')
```

**Comment by ferronrsmith** [comment]
Can you create an issue with the problem ? That statement doesn't really help us diagnose the issue

**Comment by richardwhatever** [comment]
Sure, when i try and run code like this:
```
 bb.aggregation('filter', fieldName, aggName, (a) => {
      return a.filter('nested', {path: 'skus'}, (n) => {
		return n.query('terms', { 'material': 'wood' })
		})
        .aggregation('terms', fieldName, aggName)
    })
```
BodyBuilder errors saying I can't add a query under a filter, but then elasticsearch needs it to be a query there, not filter.

**Comment by ferronrsmith** [comment]
Create a separate issue for this

**Comment by ferronrsmith** [comment]
i.e The problem also lies with your query. You are nesting a query inside a filter ... 

Have you tried ?
```javascript
 bb.aggregation('filter', fieldName, aggName, (a) => {
      return a.filter('nested', {path: 'skus'}, (n) => {
		return n.filter('terms', { 'material': 'wood' })
		})
        .aggregation('terms', fieldName, aggName)
    })
```

**Comment by eliath** [comment]
I can't seem to get nested queries to work

For example, I want:
- Match "george" in the `name` field **OR**  the `email` field.
- Filter for gender=male.

```javascript
searchQuery = 'george'
filterKey = 'gender'
filterValue = 'male'

bodybuilder()
  .query('bool', b => b
    .orQuery('match', 'name', searchQuery)
    .orQuery('match', 'email', searchQuery))
  .filter('term', filterKey, filterValue)
  .build()
```

This results in:
```javascript
{
  query: {
    bool: {
      filter: {
        term: { gender: "male" }
      },
      query: {    // <-- I want this to be "must"
        bool: {
          should: [
            { match: { name: "george" } },
            { match: { email: "george" } }
          ]
        }
      }
    }
  }
}
```

and the corresponding Elasticsearch error:
```
Error: [parsing_exception] [bool] query does not support [query]
```

What is the correct syntax to nest queries as described above?

**Comment by johannes-scharlach** [comment]
Just don't nest it inside the bool query and you should be fine. (Structure
will be slightly different to what you asked for, but results will be the
same)

**Comment by ferronrsmith** [comment]
@eliath not sure what version you are running, but when I run it with the latest. Use http://bodybuilder.js.org/ to test you queries against the latest build.

```javascript
searchQuery = 'george'
filterKey = 'gender'
filterValue = 'male'

bodybuilder()
  .query('bool', b => b
    .orQuery('match', 'name', searchQuery)
    .orQuery('match', 'email', searchQuery))
  .filter('term', filterKey, filterValue)
  .build()
```

==>

```json
{
  "query": {
    "bool": {
      "filter": {
        "term": {
          "gender": "male"
        }
      },
      "should": [
        {
          "match": {
            "name": "george"
          }
        },
        {
          "match": {
            "email": "george"
          }
        }
      ]
    }
  }
}
```

**Comment by ferronrsmith** [comment]
have u tried adding a **minimum_should_match** ?

**Comment by johannes-scharlach** [comment]
Or seeing as you don't seem to care about the scoring `orFilter` instead of `orQuery` might be right for you?

**Pull request merged**
