### PR TITLE
chore: replace lodash.set with custom util

### LINKED ISSUE #303: Dependency lodash.set has Prototype Pollution vulnerability
https://security.snyk.io/vuln/SNYK-JS-LODASHSET-1320032

I advise replacing that dependency.

### PR DESCRIPTION
**Pull request by StefOodle**
Resolves #303 Lodash.set is causing a vulnerability issue. This is the proposed solution: replacing lodash.set with a custom util.

### CODE REVIEW

**Comment by danpaz** [comment]
Thanks for PRing this. Since we are now owning the implementation of `set` that lodash previously provided I think it's worth adding a few tests to validate the behavior (especially since this is verbatim the implementation ChatGPT provided ;)). Do you mind adding some tests to this PR first before we merge it?

**Comment by StefOodle** [comment]
> Thanks for PRing this. Since we are now owning the implementation of `set` that lodash previously provided I think it's worth adding a few tests to validate the behavior (especially since this is verbatim the implementation ChatGPT provided ;)). Do you mind adding some tests to this PR first before we merge it?

It makes sense, I've added some tests. Thank you.

**Comment by danpaz** [comment]
Looks good! I'm just trying to figure out why Travis CI stopped running builds on PRs, will merge after that's fixed.

**Comment by danpaz** [comment]
Looks like Travis CI fixed the issue on their side. @StefOodle can you push an empty commit to your branch to re-trigger CI? 🙏

**Review by danpaz — APPROVED** [review]

**Pull request merged**
